<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">

<html>
    <head>
        <title>Buttons</title>
        <link rel="stylesheet" title="buttonpanel" type="text/css" href="buttonpanel.css">
        <meta http-equiv=\"Cache-Control\" content=\"no-cache, no-store, must-revalidate\" />
    </head>

<?php

/*

 Create the button panel for the Duty Review Page
 makeButtonPanel.php?EVID=$evid

*/

// Script has hard-coded host network dependencies 

include_once "phpmods/db_conn.php";
include_once "phpmods/formutils.php";
include_once "phpmods/config.php";

function url_exists($url) {
    $status = true;
    if ( strpos($url, "http:") === false ) {
      $status = file_exists($url);
    } else {
      $headers = get_headers($url);
      //$str = substr($headers[0],9,3);
      //if ( "$str" == "" || "$str" === "404" || "$str" == "403") {
      if( ! strpos($headers[0],"200") ) {
        $status = false;
      }
    }
    return $status;
}

// PASSED ARGS
$evid   = $_GET["EVID"];
// $database = $_GET["DATABASE"];

$fileroot = "../eventfiles/gifs";

$normalURL = "makeSnapshotFrame.php?EVID=${evid}";
//echo "<A HREF=\"$normalURL\" ><b>Event Trigger View</b> of $evid</A><BR>";
$normal_string = "";

// add link for synopsis gif if it exists (added 2/11/2005)
$synopsGIF = "${fileroot}/${evid}_synops.gif";
$synopsisURL = "makeSynopsisFrame.php?EVID=${evid}";
$synopsis_string = "";
if (@file_exists($synopsGIF)) { 
  $synopsis_string = "<HR><A HREF=\"${synopsisURL}\" TARGET=\"waves\"><FONT COLOR=red><B>SYNOPSIS VIEW</FONT></B></A>";
  $normal_string = "<HR><A HREF=\"${normalURL}\" TARGET=\"waves\"> <FONT COLOR=red><B>NORMAL VIEW</FONT></B></A>";
} 

// add link for scaled (filtered?) gif if it exists (added 2/28/2013)
$scaledGIF = "${fileroot}/${evid}_scaled.gif";
$scaledURL = "makeScaledFrame.php?EVID=${evid}";
$scaled_string = "";
if (@file_exists($scaledGIF)) { 
  $scaled_string = "<HR><A HREF=\"${scaledURL}\" TARGET=\"waves\"><FONT COLOR=red><B>SCALED VIEW</FONT></B></A>";
  $normal_string = "<HR><A HREF=\"${normalURL}\" TARGET=\"waves\"> <FONT COLOR=red><B>NORMAL VIEW</FONT></B></A>";
} 

// get current time in local and GMT
date_default_timezone_set('UTC');
$datestr = date("M d, Y");
$timeloc = date("G:i e");
// $timez = date("G:i");

$typeOptionStr = makeTypeOptionList("",$evid); 
$gtypeOptionStr = makeGTypeOptionList("",$evid); 

$hostname = $_SERVER['SERVER_NAME'];

// print a bunch of HTML and JavaScript almost verbatim, customized for the 'evid'
//<div class="button4" id="synb" onclick="return toggleButtons();><A HREF=\"${synopsisURL}\" TARGET=\"waves\"> SYN VIEW</A></div>
//<div class="button4" id="trgb" onclick="return toggleButtons();><A HREF=\"${trgURL}\" TARGET=\"waves\"> TRG VIEW</A></div>

// Kludge here adds button for focal mec view if event ever has autogenerated ones available:
$lcNet = strtolower($networkCode);

$focmecMT_string = "";
$focmecAR_string = "";
$focmecFP1_string = "";
$focmecFP2_string = "";

//Example local tmts2 template: $focmecFile = "web_15292545/ci15292545_MT.html";
$focmecFile = "web_${evid}/${lcNet}${evid}_MT.html";
$focmecURL = "${mtFocmecURL}/${focmecFile}";
if (@url_exists($focmecURL)) { 
    $focmecMT_string = "<HR><A HREF=\"${focmecURL}\" TARGET=\"mt-fm\"> <FONT COLOR=red><B>FOCMEC MT</FONT></B></A>";
    $normal_string = "<HR><A HREF=\"${normalURL}\" TARGET=\"waves\"> <FONT COLOR=red><B>NORMAL VIEW</FONT></B></A>";
}

// First try for H flag source
//Example local fpfit template: $focmecFile = "${lcNet}15275793.${lcNet}fm1.html";
$focmecFile = "${lcNet}${evid}.${lcNet}fm1.html";
$focmecURL = "${fpFocmecURL_H}/${focmecFile}";
if (@file_exists($focmecURL)) { 
    $focmecFP1_string = "<HR><A HREF=\"${focmecURL}\" TARGET=\"fpfit-H1\"> <FONT COLOR=red><B>FOCMEC FP-1H</FONT></B></A>";
    $normal_string = "<HR><A HREF=\"${normalURL}\" TARGET=\"waves\"> <FONT COLOR=red><B>NORMAL VIEW</FONT></B></A>";
    $focmecFile = "${lcNet}${evid}.${lcNet}fm2.html";
    $focmecURL = "${fpFocmecURL_H}/${focmecFile}";
    if (@file_exists($focmecURL)) { 
        $focmecFP2_string = "<HR><A HREF=\"${focmecURL}\" TARGET=\"fpfit-H2\"> <FONT COLOR=red><B>FOCMEC FP-2H</FONT></B></A>";
        $normal_string = "<HR><A HREF=\"${normalURL}\" TARGET=\"waves\"> <FONT COLOR=red><B>NORMAL VIEW</FONT></B></A>";
    }
}
else { // no H so try for Auto source
    $focmecFile = "${lcNet}${evid}.${lcNet}fm1.html";
    $focmecURL = "${fpFocmecURL_A}/${focmecFile}";
    if (@file_exists($focmecURL)) { 
      $focmecFP1_string = "<HR><A HREF=\"${focmecURL}\" TARGET=\"fpfit-A1\"> <FONT COLOR=red><B>FOCMEC FP-1A</FONT></B></A>";
      $normal_string = "<HR><A HREF=\"${normalURL}\" TARGET=\"waves\"> <FONT COLOR=red><B>NORMAL VIEW</FONT></B></A>";
      $focmecFile = "${lcNet}${evid}.${lcNet}fm2.html";
      $focmecURL = "${fpFocmecURL_A}/${focmecFile}";
      if (@file_exists($focmecURL)) { 
          $focmecFP2_string = "<HR><A HREF=\"${focmecURL}\" TARGET=\"fpfit-A2\"> <FONT COLOR=red><B>FOCMEC FP-2A</FONT></B></A>";
          $normal_string = "<HR><A HREF=\"${normalURL}\" TARGET=\"waves\"> <FONT COLOR=red><B>NORMAL VIEW</FONT></B></A>";
      }
    }
}
//Example local HASH fmar? template: $focmecFile = "${lcNet}15275793.${lcNet}fm1.html";
$focmecFile = "${lcNet}${evid}.${lcNet}fm1.html";
$focmecURL = "${arFocmecURL}/${focmecFile}";
if (@file_exists($focmecURL)) { 
    $focmecAR_string = "<HR><A HREF=\"${focmecURL}\" TARGET=\"fmar-A1\"> <FONT COLOR=red><B>FOCMEC AR</FONT></B></A>";
    $normal_string = "<HR><A HREF=\"${normalURL}\" TARGET=\"waves\"> <FONT COLOR=red><B>NORMAL VIEW</FONT></B></A>";
}

$webicorderString = "";
if ( url_exists("$webicorderURL") ) {
  //$webicorderString = "<a style=\"background-color: gray\" HREF=\"$webicorderURL\" TARGET=\"_top\">Helicorders</A>";
  $now= time();
  $webicorderString = "<a style=\"background-color: gray\" HREF=\"${webicorderURL}index.html?v=${now}\" TARGET=\"_blank\">Helicorders</A>";
}

print <<<end_text
<body>

<Center>

<b>Last catalog refresh:<br>
$datestr&nbsp;$timeloc<br>
ID = $evid<br>

DB = $db_name</b><br>

<div id="csscontainer">

<div class="button4">
<a style="background-color: LimeGreen" 
   href="#" onclick="acceptIt(); return false;" name="accBut">Accept</a>
<IMG SRC="../../images/clearpixel.gif" WIDTH="0" HEIGHT="0" HSPACE="1" VSPACE="3"  Border=0>
<a style="background-color: orange" 
   href="#" onclick="cancelIt(); return false;" name="delBut">Cancel</a>
<IMG SRC="../../images/clearpixel.gif" WIDTH="0" HEIGHT="0" HSPACE="1" VSPACE="3"  Border=0>
<a style="background-color: black" 
   href="#" onclick="finalizeIt(); return false;" name="finBut">Finalize</a>
<IMG SRC="../../images/clearpixel.gif" WIDTH="0" HEIGHT="0" HSPACE="1" VSPACE="3"  Border=0>
<a style="background-color: red" 
   href="#" onclick="deleteIt(); return false;" name="canBut">Delete</a>
</div>

<div class="button4">
<table><tr>
<td>
<a style="width: 3.6em; text-align: center; background-color: tan; color: black"
   href="#" onclick="loadEarlier(); return false;" name="downBut" >
   <img src="../../images/trans_arrow_down.gif" alt="Down" 
        title="Jump to earlier event (down list)"  border=0 >
</a>
</td>
<td>
<a style="width: 3.6em; text-align: center; font-weight: bold; background-color: tan; color: black"
   href="#" onclick="loadLater(); return false;" name="upBut">
  <img src="../../images/trans_arrow_up.gif" alt="Up" 
       title="Jump to later event (up list)"  border=0 >
</a>
</td>
</tr></table>
</div>
${normal_string}
${synopsis_string}
${scaled_string}
${focmecMT_string}
${focmecAR_string}
${focmecFP1_string}
${focmecFP2_string}

<hr>
<DIV class="left">
<B>ET:</B>
<SELECT Name=EventType Size=1 
  onChange="setType(this[selectedIndex].value); return false;">
<OPTION>-choose-
${typeOptionStr}
</SELECT>
</DIV>

<DIV class="left">
<B>GT:</B>
<SELECT Name=EventGType Size=1 
  onChange="setGType(this[selectedIndex].value); return false;">
<OPTION>-choose-
${gtypeOptionStr}
</SELECT>
</DIV>

<!-- Script has hard-coded host network dependencies -->

<div class="button4">
<!--  <a href="makeEmailPanel.php?EVID=${evid}" TARGET="waves" name="mailBut">Send E-mail</a>
 <a href="#" onclick="makePublicWebPage(); return false;" name="webBut">Make Web Page</a> -->

  <!-- NOT READY YET
  <a style="background-color: orange" href="#" onclick="resendQDDS(); return false;" name="qddsBut">Send QDDS</a>
  -->
</div>

<div class="button4">
  <a style="background-color: DeepPink" href="#" onClick="showEditMag();  return false;" name="magBut">Edit Magnitude</a>
  <a style="background-color: DeepPink" href="#" onClick="showEditDepth();  return false;" name="depthBut">Edit Depth</a>
  <a style="background-color: DeepPink" href="#" onclick="resendAlarms(); return false;" name="alarmBut">Resend Alarms</a>
  <a style="background-color: DeepPink" href="#" onclick="remakeGif(); return false;" name="gifBut">Remake GIF</a>
</div>

<div class="button4">
  <a style="background-color: DarkGreen" HREF="#" onClick="showSimpson(); return false;">USGS Event Page</A>
  <a style="background-color: DarkGreen" HREF="http://scedc.caltech.edu/recent/Quakes/ci${evid}.html" TARGET="_blank">SCEDC Event Page</A>
  <a style="background-color: DarkGreen" HREF="https://earthquake.usgs.gov/earthquakes/eventpage/$networkCode$evid#scientific" TARGET="parent">Distributed Products</A>
</div>

<div class="button4">
  <a style="background-color: Orchid" HREF="http://$hostname/duty/dutychk.html" TARGET="_blank">Duty Checklist</A>
  <a style="background-color: Orchid" href="#" onClick="showFusionTable();  return false;" name="fusionBut">Duty Alarm Map</a>
  <a style="background-color: Orchid" HREF="http://$hostname/admin/dutylist.php" TARGET="_blank">Duty Roster</A>
</div>

<div class="button4">
  <a style="background-color: DarkTurquoise" HREF="../ShakemapRegions/Shakemap Regions.htm" TARGET="parent">Shakemap Regions</A>
  <a style="background-color: DarkTurquoise" HREF="./ShakemapInstructions.html" TARGET="parent">Shakemap Manual</A>
</div>

<div class="button4">
  <a style="background-color: gray" href="#" onclick="showLog(); return false;" name="logBut">Show Log</a>
  <a style="background-color: gray" HREF="http://vault.gps.caltech.edu/trac/cisn/wiki/DutyReview" TARGET="parent">DRP Doc</A>
  <a style="background-color: gray" HREF="./reviewOptions.html" TARGET="parent">Change Password</A>
  <a style="background-color: gray" HREF="../trigger.php" TARGET="_top">Trigger Page</a>
  <a style="background-color: gray" HREF="../../index.html" TARGET="_top"> AQMS Home </A>
  ${webicorderString}
</div>


<!-- end of csscontainer div -->
</div>

<SCRIPT TYPE="text/JavaScript"> 

<!-- Hide if browser can not cope ------------------------------------------------------
// Get necessary parameters from the 'catalog' frame
    var id = top.catalog.getCurrentId();
    var dbase = top.catalog.getDbase();
    var testWin = null;
    var flag = top.catalog.getCurrentFlag();

    var str = "Event " + id + " rflag=" + flag;
    if ( flag == 'C' ) {
      str += " (CANCELLED)"
    }
    else if ( flag == 'I' ) {
      str += " (INTERIM)"
    }
    else if ( flag == 'F' ) {
      str += " (FINALIZED)"
    }
    else if ( flag == 'H' ) {
      str += " (HUMAN)"
    }
    else if ( flag == 'A' ) {
      str += " (AUTOMATIC)"
    }
    str += "\\n\\n";

// ---------------------
function acceptIt() {

  var doit = true;

  if ( flag != 'A' ) {
    doit = false;

    doit = window.confirm(str + "RESET origin rflag='H' and do ALARMS ?");
  }

  if ( doit ) {
      action = "doAction.php?EVID=" + id + "&ACTION=accept&DATABASE=" + dbase;
      if (testWin == null) { testWin = window.open ("","logwindow") }
      testWin.location.href= action;

      loadEarlier();  // jump to next event
  }
}
// ---------------------
function deleteIt() {

 if ( window.confirm(str + "DELETE (set event selectFlag=0) and do CANCEL ALARMS ?") )
 {
    action = "doAction.php?EVID=" + id + "&ACTION=delete&DATABASE=" + dbase;
    if (testWin == null) { testWin = window.open ("","logwindow") }
    testWin.location.href= action;

    loadEarlier();  // jump to next event
 }

}
// ---------------------
function cancelIt() {

 if ( window.confirm(str + "Do CANCEL ALARMS (does not delete event) ?") )
 {
    action = "doAction.php?EVID=" + id + "&ACTION=cancel&DATABASE=" + dbase;
    if (testWin == null) { testWin = window.open ("","logwindow") }
    testWin.location.href= action;

    loadCurrent();
  }
 
}

// ---------------------
function resendAlarms() {

  if ( window.confirm(str + "Post to DISTRIBUTE (do ALARMS)?") )
  {

    action = "doAction.php?EVID=" + id + "&ACTION=alarm&DATABASE=" + dbase;

    if (testWin == null) { testWin = window.open ("","logwindow") }
    testWin.location.href= action;

    loadCurrent();  // stay with current event 

  }
}

// ---------------------
function finalizeIt() {

  if ( window.confirm(str + "Post to DISTRIBUTE (do ALARMS)?") )
  {

    action = "doAction.php?EVID=" + id + "&ACTION=finalize&DATABASE=" + dbase;

    if (testWin == null) { testWin = window.open ("","logwindow") }
    testWin.location.href= action;

    loadCurrent();  // stay with current event 

  }
}

/*
// --------------------- NOT USED
function resendQDDS() {

    action = "doAction.php?EVID=" + id + "&ACTION=qdds";

    if (testWin == null) { testWin = window.open ("","logwindow") }
    testWin.location.href= action;

    loadEarlier();  // jump to next event
}
*/

function remakeGif() {

  if ( window.confirm( str + "Post evid to MakeGif?\\n" +
                        "NOTE: This will take minutes to process." ) )
  {

      action = "doAction.php?EVID=" + id + "&ACTION=MAKEGIF&DATABASE=" + dbase;

      if (testWin == null) { testWin = window.open ("","logwindow") }
      testWin.location.href= action;

      loadEarlier();  // jump to next event
  }
}

function setType(type) {

    action = "doAction.php?EVID=" + id + "&ACTION=SET_TYPE&TYPE=" + type
             + "&DATABASE=" + dbase;
    if (testWin == null) { testWin = window.open ("","logwindow") }
    testWin.location.href= action;
}

function setGType(type) {

    action = "doAction.php?EVID=" + id + "&ACTION=SET_GTYPE&GTYPE=" + type
             + "&DATABASE=" + dbase;
    if (testWin == null) { testWin = window.open ("","logwindow") }
    testWin.location.href= action;
}

/*
// --------------------- NOT USED
// Create a link on the main web page to an event summary page

function makePublicWebPage () {
    if ( window.confirm ("THIS IS DEFUNCT") ) {
        newwin = window.open ("http://earthquake.usgs.gov/eqcenter/eqinthenews/control/","")
    }
}
*/

//---------------------
// Show the last entries in the delete/accept log file in a new window
function showLog() {
   if ( testWin != null) { testWin.close(); } 
   testWin = window.open("logAsHtml.php#bottom", "logwindow");
	//"height=350,width=900,toolbar=no,menubar=no," + 
	//"resizable=yes,scrollbars=yes")
   testWin.focus();
}

//---------------------
// - Note mag editing was combined with EditLoc which is disabled
function showEditMag() {

   editwindow = window.open("magEditPanel.php?EVID=" + id + "&DATABASE=" +  dbase,
                           "editwindow",
                           "height=600,width=350,toolbar=no,menubar=no," + 
                           "resizable=yes,scrollbars=yes")
   editwindow.focus();
}

//---------------------
// - Edit the depth of an event
function showEditDepth() {

   editwindow = window.open("depthEditPanel.php?EVID=" + id + "&DATABASE=" +  dbase,
                           "editwindow",
                           "height=600,width=350,toolbar=no,menubar=no," + 
                           "resizable=yes,scrollbars=yes")
   editwindow.focus();
}

//---------------------
// - Show the fusion table
function showFusionTable() {

   editwindow = window.open("FusionTable.html","editwindow")
//                           "height=650,width=1050,toolbar=no,menubar=no," + 
//                           "resizable=yes,scrollbars=yes")
   editwindow.focus();
}

/*
// --------------------- NOT USED
function showEditLoc() {

   editwindow = window.open ("locEditPanel.php?EVID=" + id, "editwindow",
        "height=700,width=400,toolbar=no,menubar=no," + 
        "resizable=yes,scrollbars=yes")
   editwindow.focus();
}
*/

//---------------------
function showSimpson () {

end_text;

// In php interpreter transfer php config vars into javascript text:
echo "    var networkCode  = \"$networkCode\";\n";
echo "    var recEqRootURL = \"$recEqRootURL\";\n";
echo "    var netC = new String(networkCode.toLowerCase());\n";
// resume print of javascript text

print <<<end_text2

    //var url = "http://earthquake.usgs.gov/earthquakes/recenteqsus/Quakes/" + netC + evid + ".html";
    //var url = "http://earthquake.usgs.gov/earthquakes/eventpage/" + netC + id + "#technical";
    //var url = recEqRootURL + "/eventpage/ci" + id + "#summary";

    var url = recEqRootURL + "/eventpage/" + netC + id + "#summary";
    simpsonWindow = window.open (url, "simpsonWindow", "toolbar=yes,menubar=yes, height=600,width=900, resizable=yes,scrollbars=yes");

}

//---------------------
function loadLater () {
    var id = top.catalog.nextIndexUp();
    top.catalog.selectNewEvidAndScroll(top.catalog.getId(id), 1);
}


//---------------------
function loadEarlier () {
    var id = top.catalog.nextIndexDown();
    top.catalog.selectNewEvidAndScroll(top.catalog.getId(id), 1);
}


// -------------------
function loadCurrent() {
    top.catalog.selectDefaultEvidAndScroll(0);
}

// End of hide comment -->

</SCRIPT>

</body>

end_text2;

?>

</html>
